### ISSUE TITLE
Enable deployment of bentoML to AWS Inf1 instances

### ISSUE THREAD

**Issue by Matthieu-Tinycoaching** [bentoml/aws-ec2-deploy#16]
Hello,

Would it be possible to customize bentoML service to enable deployment into AWS Inf1 instances using Neuron library (https://awsdocs-neuron.readthedocs-hosted.com/en/latest/index.html) ?

Thanks!

**Comment by parano** [comment]
This should be supported now via the `instance_type` option provided via the deployment config file https://github.com/bentoml/aws-ec2-deploy/blob/pre-v1.0/ec2_config.json
