### ISSUE TITLE
Customize docker environment for the EC2 deployment

### ISSUE THREAD

**Issue by Matthieu-Tinycoaching** [bentoml/aws-ec2-deploy#17]
When deploying bentoML service onto an AWS EC2 instance, it for now impossible to customize the docker environment such as activating microbatching via `BENTOML_ENABLE_MICROBATCH` and add further gunicorn workers via `BENTOML_GUNICORN_WORKERS`.

Could it be possible to develop these customizations which are really needed regarding to microbatching when deploying on cloud.

**Comment by parano** [comment]
With the new `bentoctl` tool and its `aws-ec2-deploy` plugin, it is now possible to customize environment variables of an EC2 deployment, via the `environment_variables` option in the deployment config file: https://github.com/bentoml/aws-ec2-deploy/blob/pre-v1.0/ec2_config.json
