### ISSUE TITLE
ModuleNotFoundError: No module named 'bentoml.saved_bundle'

### ISSUE THREAD

**Issue by aarunjith** [bentoml/aws-ec2-deploy#18]
Get this error when trying to execute the following code
**python deploy.py C:\Users\arunjith\bentoml\bentos\gbm_test\zzyycql7m625kthn**

bentoml list gives out the following output.
 Tag                        Service    Path                                                        Size      Creation Time
 gbm_test:zzyycql7m625kthn  bento:svc  C:\Users\arunjith\bentoml\bentos\gbm_test\zzyycql7m625kthn  9.18 MiB  2022-01-27 11:53:57

**Comment by jjmachan** [comment]
can you share which bentoml version you are using and which branch of the aws-ec2-deploy you are on?
if you are using bentoml 1.0 then you can checkout the main branch (which is updated for 1.0) or the bentoctl tool

**Comment by aarunjith** [comment]
The bentoml version seems to be 1.00a. I was using the pre-v1.0 branch. Let me try the main branch

**Comment by aarunjith** [comment]
I was trying to follow the instruction for the main branch. Although I installed bentoctl using pip, my cmd says that bentoctl command is not recognized. Should I manually add this to the PATH or something?

**Comment by jjmachan** [comment]
No you don't have to add it into the path. You can install it with `pip install --pre bentoctl` and it should install the latest, pre-release version

can you put the output of the pip install command and also the output from `pip show bentoctl`

**Comment by aarunjith** [comment]
![after](https://user-images.githubusercontent.com/34453139/151759173-5d0f71f5-df8a-42f8-b554-112fadfbb522.PNG)
![before](https://user-images.githubusercontent.com/34453139/151759179-99434828-80e7-43e6-bbf8-946ae785974b.PNG)

But looks like the issue of not finding bentoctl is resolved after uninstalling and installing with the --pre flag. Thank you.

**Comment by jjmachan** [comment]
glad it helped!
