### ISSUE TITLE
Permissions issue when creating S3 Bucket

### ISSUE THREAD

**Issue by paulommaia** [bentoml/aws-ec2-deploy#9]
I was able the demo with the Iris Classifier once but on the second time I had some permissions issue with the S3 Bucket

  File "/home/paulo/bentoml_tutorial/aws-ec2-deploy/utils/__init__.py", line 101, in create_s3_bucket_if_not_exists

`botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the GetBucketAcl operation: Access Denied`

And when running delete afterwrads:
`botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the ListObjects operation: Access Denied` 

The lambda function deployment worked fine for me

**Comment by jjmachan** [comment]
can you check your IAM role and give it the permissions to `GetBucketAcl` Actions or S3 permissions in general? The Deployment tool uses the Profile that is active in your AWS Cli so that could be an issue (incorrect permission to the profile in use)

**Comment by jjmachan** [comment]
The S3 dependency is now removed and so this should not be an issue now, @paulommaia can you pull the latest changes and try again? it should fix this issue.

**Comment by yubozhao** [comment]
close it for now. Feel free to reopen it @paulommaia

**Comment by paulommaia** [comment]
Thank you! I will test it ASAP, busy with some other stuff this week :)
